# Generated by Django 4.0.2 on 2022-02-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='multipleSearchFields',
            fields=[
                ('emid', models.IntegerField(primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('occapation', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
